GET http://localhost:5052
###
GET http://localhost:5052/segundo
###
GET http://localhost:5052/retorno
###
POST http://localhost:5052/adicionar
###
GET http://localhost:5052/produto/listar
###
POST http://localhost:5052/produto/cadastrar/Pablo